name: Create Release

# Trigger the workflow when a new tag is pushed
on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

jobs:
  # Job to create GitHub release
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes

            See [CHANGELOG.md](CHANGELOG.md) for detailed changes.

            ## Installation

            Add this to your package's `pubspec.yaml` file:

            ```yaml
            dependencies:
              biometric_authorization: ^${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
